# Generated by Django 2.2.6 on 2019-10-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191029_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bad_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_fb', models.CharField(max_length=200)),
                ('feedback_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Feedback_Choice')),
            ],
        ),
    ]
