# Generated by Django 2.2.6 on 2019-10-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_bad_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bad_Fb_Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etc_bad_text', models.CharField(max_length=200)),
                ('bad_fb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Bad_Feedback')),
            ],
        ),
    ]
