# Generated by Django 2.2.6 on 2019-10-30 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_bad_fb_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bad_fb_choice',
            name='bad_fb',
        ),
        migrations.AddField(
            model_name='bad_fb_choice',
            name='feedback_c',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='polls.Feedback_Choice'),
        ),
        migrations.DeleteModel(
            name='Bad_Feedback',
        ),
    ]
