# Generated by Django 2.2.6 on 2019-10-30 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20191030_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bad_Fb_Choice',
            new_name='Fb_Choice_Data',
        ),
    ]
