# Generated by Django 2.2.6 on 2019-10-30 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20191030_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fb_choice_data',
            old_name='etc_bad_text',
            new_name='fb_etc_text',
        ),
    ]
